env:
  global:
    - LC_CTYPE=en_US.UTF-8

branches:
  only:
    - develop
    - master

os: osx
language: objective-c
matrix:
  exclude:
    - os: osx
  include:
    - osx_image: xcode9.2
      env:
        - XCODE_ACTION="clean test"
          XCODE_TOOLCHAIN="swift"
          XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - osx_image: xcode8
      env:
        - JOB=CARTHAGE
      script:
        - brew update 1> /dev/null 2> /dev/null
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current
        - test -d Carthage/Build/iOS/RIGImageGallery.framework || exit 1
    - osx_image: xcode9.2
      env:
        - JOB=COCOAPODS
      script:
        - bundle exec pod lib lint --sources="https://github.com/Raizlabs/RIGImageGallery"

before_script:
  - killall "Simulator" || echo "No matching processes belonging to you were found"

script:
  - travis_retry xcodebuild ${XCODE_ACTION}
    -toolchain ${XCODE_TOOLCHAIN}
    -project RIGImageGallery.xcodeproj
    -scheme RIGImageGallery
    -destination "${XCODE_DESTINATION}"
